# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cbffce06b6e78badaa806ad9ef367f944a77a44895a0a8894c999c36196c082bf01da7ab6e51418cf27cc616076e3ba9254973040dca1efba10b70bb5f29cf08

test:
  secret_key_base: 43dcaf72e1a360fcc07e994ce94aa1fa35c8d4c13ca2e01e55d85d8d3e93fe429e2296dc8a38ffdeec117b5fb7968275993e6cfa858ea0a60157d2ca4ccc52b8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
